
package uytube.web.wsclients;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CanalRepetidoException", targetNamespace = "http://interfaces/")
public class CanalRepetidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CanalRepetidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CanalRepetidoException_Exception(String message, CanalRepetidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CanalRepetidoException_Exception(String message, CanalRepetidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: uytube.web.wsclients.CanalRepetidoException
     */
    public CanalRepetidoException getFaultInfo() {
        return faultInfo;
    }

}
