
package uytube.web.wsclients;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CategoriaRepetidaException", targetNamespace = "http://interfaces/")
public class CategoriaRepetidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CategoriaRepetidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CategoriaRepetidaException_Exception(String message, CategoriaRepetidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CategoriaRepetidaException_Exception(String message, CategoriaRepetidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: uytube.web.wsclients.CategoriaRepetidaException
     */
    public CategoriaRepetidaException getFaultInfo() {
        return faultInfo;
    }

}
