
package uytube.web.wsclients;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ControladorUsuarioService", targetNamespace = "http://controladores/", wsdlLocation = "http://localhost:17184/UsuarioWs?wsdl")
public class ControladorUsuarioService
    extends Service
{

    private final static URL CONTROLADORUSUARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTROLADORUSUARIOSERVICE_EXCEPTION;
    private final static QName CONTROLADORUSUARIOSERVICE_QNAME = new QName("http://controladores/", "ControladorUsuarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:17184/UsuarioWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTROLADORUSUARIOSERVICE_WSDL_LOCATION = url;
        CONTROLADORUSUARIOSERVICE_EXCEPTION = e;
    }

    public ControladorUsuarioService() {
        super(__getWsdlLocation(), CONTROLADORUSUARIOSERVICE_QNAME);
    }

    public ControladorUsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTROLADORUSUARIOSERVICE_QNAME, features);
    }

    public ControladorUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, CONTROLADORUSUARIOSERVICE_QNAME);
    }

    public ControladorUsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTROLADORUSUARIOSERVICE_QNAME, features);
    }

    public ControladorUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ControladorUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IControladorUsuario
     */
    @WebEndpoint(name = "ControladorUsuarioPort")
    public IControladorUsuario getControladorUsuarioPort() {
        return super.getPort(new QName("http://controladores/", "ControladorUsuarioPort"), IControladorUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IControladorUsuario
     */
    @WebEndpoint(name = "ControladorUsuarioPort")
    public IControladorUsuario getControladorUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controladores/", "ControladorUsuarioPort"), IControladorUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTROLADORUSUARIOSERVICE_EXCEPTION!= null) {
            throw CONTROLADORUSUARIOSERVICE_EXCEPTION;
        }
        return CONTROLADORUSUARIOSERVICE_WSDL_LOCATION;
    }

}
